services:
  feeder:
    build: .
    container_name: experiment-feeder-python
    env_file:
      - .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
